version: '3.3'
services:
  workflow-api-users:
    image: node:16
    ports:
      - "3000:3000"
    working_dir: /src
    networks:
      - app-network
    depends_on:
        - workflow-db-users
    environment:
      HOST: 0.0.0.0
    command: bash -c "npm install -f && npm run start:dev"
    volumes:
      - "./:/src"
      - "/src/node_modules"

  workflow-db-users:
    container_name: workflow-db-users
    image: postgres:9.5
    restart: always
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
      - ./_postgres/scripts/create_test_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432

  workflow-pgadmin-users:
    container_name: workflow-pgadmin-users
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin/web/pgadmin4
networks:
  app-network:
    driver: bridge
volumes:
  workflow-api-users:
  workflow-pgadmin-users:
  workflow-db-users: