version: '3.3'
services:
  workflow-api-users:
    image: node:16
    ports:
      - "4000:4000"
    working_dir: /src
    networks:
      - app-network
    environment:
      DATABASE_HOST: workflow-db-user
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: root
      DATABASE_NAME: user
    command: bash -c "npm install -f && npm start"
    depends_on:
      - workflow-db-users
    volumes:
      - ":/src"
      - "/src/node_modules"

  workflow-db-users:
    image: kartoza/postgis:14-3.1
    volumes:
      - ../workflow-db-user:/var/lib/postgresql
      - ../workflow-db-users_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=root
      - POSTGRES_DB=user
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    networks:
      - app-network

  workflow-pgadmin-users:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ../workflow-pgadmin-user:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  workflow-api-users:
  workflow-pgadmin-users:
  workflow-db-users: